#!/usr/bin/env bash
# AI Agent 赛道 tracker daily runner.
set -euo pipefail

cd "$(dirname "$0")"
LOG_DATE=$(date +%Y-%m-%d)
echo "[$(date)] AI Agent tracker starting…"

# Source env (Discord webhook + Claude OAuth + proxy)
if [[ -f /Users/cherie/projects/Antigravity/ag-worker/load_env.sh ]]; then
  set +u
  source /Users/cherie/projects/Antigravity/ag-worker/load_env.sh
  set -u
fi

# Run main tracker (claude CLI fetch + diff + generate)
python3 scripts/run_tracker.py

# index.html already written by run_tracker (it overwrites with latest)
echo "  → reports/${LOG_DATE}_ai_agents.{md,html} produced"

# commit + push if there are changes (skip if no git remote yet)
if git remote get-url origin > /dev/null 2>&1; then
  if [[ -n "$(git status --porcelain)" ]]; then
    git add reports/ index.html data/sources_state.json
    git commit -m "daily snapshot ${LOG_DATE}" \
               -m "auto-generated by runner.sh" || true
    git push origin main || echo "  → push failed (non-fatal)"
  else
    echo "  → no changes to commit"
  fi
else
  echo "  → no git remote configured yet, skipping push"
fi

echo "[$(date)] done."
